name: Docker

on:
  push:
    paths:
    - .github/workflows/docker.yaml
    - '**/Dockerfile'
    - '**/docker-entrypoint.sh'

jobs:

  build-1_10:

    name: Build 1.10
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        docker build \
        --pull \
        --no-cache \
        --tag bowens/composer:1 \
        --tag bowens/composer:$(grep -oE 'COMPOSER_VERSION 1.[0-9]+.[0-9]+' Dockerfile | grep -oE '1.[0-9]+.[0-9]+') \
        .
      working-directory: '1.10'

    - name: Registry login
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push tag(s)
      if: github.ref == 'refs/heads/master'
      run: |
        docker push bowens/composer:1
        docker push bowens/composer:$(grep -oE 'COMPOSER_VERSION 1.[0-9]+.[0-9]+' Dockerfile | grep -oE '1.[0-9]+.[0-9]+')
      working-directory: '1.10'

  build-2_0:

    name: Build 2.0
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        docker build \
        --pull \
        --no-cache \
        --tag bowens/composer:latest \
        --tag bowens/composer:2 \
        --tag bowens/composer:$(grep -oE 'COMPOSER_VERSION 2.[0-9]+.[0-9]+' Dockerfile | grep -oE '2.[0-9]+.[0-9]+') \
        .
      working-directory: '2.0'

    - name: Registry login
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push tag(s)
      if: github.ref == 'refs/heads/master'
      run: |
        docker push bowens/composer:latest
        docker push bowens/composer:2
        docker push bowens/composer:$(grep -oE 'COMPOSER_VERSION 2.[0-9]+.[0-9]+' Dockerfile | grep -oE '2.[0-9]+.[0-9]+')
      working-directory: '2.0'
